trigger:
  branches:
    include:
      - main

variables:
  acrName: 'campusbookingacr'
  resourceGroup: 'campus-booking-rg'
  backendApp: 'campus-booking-backend-api'
  frontendApp: 'campus-booking-frontend-web'
  backendUrl: 'https://campus-booking-backend-api.azurewebsites.net'

stages:
  # BUILD STAGE
  - stage: Build
    displayName: 'Build and Push Images'
    jobs:
      - job: BuildBackend
        displayName: 'Build Backend'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: 'Build Backend Image'
            inputs:
              containerRegistry: 'campusbookingacr-connection'
              repository: 'backend'
              command: 'build'
              Dockerfile: 'backend/Dockerfile'
              tags: '$(Build.BuildId)'
          
          - task: Docker@2
            displayName: 'Push Backend Image'
            inputs:
              containerRegistry: 'campusbookingacr-connection'
              repository: 'backend'
              command: 'push'
              tags: '$(Build.BuildId)'

      - job: BuildFrontend
        displayName: 'Build Frontend'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              cd frontend
              echo "REACT_APP_API_URL=$(backendUrl)" > .env.production
            displayName: 'Create Frontend .env.production'
          
          - task: Docker@2
            displayName: 'Build Frontend Image'
            inputs:
              containerRegistry: 'campusbookingacr-connection'
              repository: 'frontend'
              command: 'build'
              Dockerfile: 'frontend/Dockerfile'
              tags: '$(Build.BuildId)'
          
          - task: Docker@2
            displayName: 'Push Frontend Image'
            inputs:
              containerRegistry: 'campusbookingacr-connection'
              repository: 'frontend'
              command: 'push'
              tags: '$(Build.BuildId)'

  # DEPLOY STAGE
  - stage: Deploy
    displayName: 'Deploy to Azure'
    dependsOn: Build
    jobs:
      - deployment: DeployBackend
        displayName: 'Deploy Backend'
        environment: 'production'
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebAppContainer@1
                  displayName: 'Deploy Backend Container'
                  inputs:
                    azureSubscription: 'azure-students-connection'
                    appName: '$(backendApp)'
                    containers: '$(acrName).azurecr.io/backend:$(Build.BuildId)'

      - deployment: DeployFrontend
        displayName: 'Deploy Frontend'
        environment: 'production'
        dependsOn: DeployBackend
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebAppContainer@1
                  displayName: 'Deploy Frontend Container'
                  inputs:
                    azureSubscription: 'azure-students-connection'
                    appName: '$(frontendApp)'
                    containers: '$(acrName).azurecr.io/frontend:$(Build.BuildId)'