trigger:
  branches:
    include:
      - main

variables:
  # Names of your Azure resources
  acrName: 'campusbookingacr'
  resourceGroup: 'campusbookingrg'
  backendAppName: 'campus-booking-backend-api'
  frontendAppName: 'campus-booking-frontend-web'
  
  # URL used to build the frontend
  backendUrl: 'https://campus-booking-backend-api.azurewebsites.net/api'
  
  # Name of your Azure subscription service connection
  azureSubscription: 'azure-students-connection'

stages:
# ========== STAGE 1: BUILD AND PUSH DOCKER IMAGES ==========
- stage: Build
  displayName: 'Build and Push Images'
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push to ACR'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    
    # Build and Push Backend Image
    - task: Docker@2
      displayName: 'Build and Push Backend'
      inputs:
        containerRegistry: 'campusbookingacr-connection'
        repository: 'backend'
        command: 'buildAndPush'
        Dockerfile: 'backend/Dockerfile'
        tags: '$(Build.BuildId)'

    # Create .env file for Frontend build
    - script: |
        echo "REACT_APP_API_URL=$(backendUrl)" > frontend/.env.production
      displayName: 'Create Frontend .env file'

    # Build and Push Frontend Image
    - task: Docker@2
      displayName: 'Build and Push Frontend'
      inputs:
        containerRegistry: 'campusbookingacr-connection'
        repository: 'frontend'
        command: 'buildAndPush'
        Dockerfile: 'frontend/Dockerfile'
        buildContext: 'frontend'
        tags: '$(Build.BuildId)'

# ========== STAGE 2: TERRAFORM VALIDATION ==========
- stage: TerraformValidate
  displayName: 'Validate Terraform Configuration'
  dependsOn: []  # Runs independently
  jobs:
  - job: Validate
    displayName: 'Terraform Validation'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'
    
    - bash: |
        cd terraform
        terraform init -backend=false
        terraform fmt -check
        terraform validate
        echo "✓ Terraform configuration is valid"
      displayName: 'Validate Terraform Code'

# ========== STAGE 3: DEPLOY APPS ==========
- stage: Deploy
  displayName: 'Deploy Applications'
  dependsOn: Build
  jobs:
  - deployment: DeployProduction
    displayName: 'Deploy to Production'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: 'Deploy Backend App'
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(backendAppName)
              containers: '$(acrName).azurecr.io/backend:$(Build.BuildId)'

          - task: AzureWebAppContainer@1
            displayName: 'Deploy Frontend App'
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(frontendAppName)
              containers: '$(acrName).azurecr.io/frontend:$(Build.BuildId)'