# azure-pipelines.yml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Define the production backend URL for the frontend build
  REACT_APP_API_URL: 'https://campus-booking-backend-api.azurewebsites.net/api'

steps:
# ========== BUILD BACKEND ==========
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build --if-present
  displayName: 'Build Backend'
  workingDirectory: 'backend'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'backend'
    artifactName: 'backend-app'
  displayName: 'Publish Backend Artifact'

# ========== BUILD FRONTEND ==========
- script: |
    # Create a .env file with the production URL from the pipeline variables
    echo "REACT_APP_API_URL=$(REACT_APP_API_URL)" > .env
    npm install
    npm run build
  displayName: 'Build Frontend'
  workingDirectory: 'frontend'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'frontend/build'
    artifactName: 'frontend-app'
  displayName: 'Publish Frontend Artifact'