version: '3.8'

services:
  backend:
    build: ./backend
    container_name: campus-booking-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    networks:
      - campus-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: campus-booking-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - campus-network

networks:
  campus-network:
    driver: bridge